server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/pagatu_orden_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/
